// <auto-generated />
namespace SecretSanta.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addotherentitiesandconfigurations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addotherentitiesandconfigurations));
        
        string IMigrationMetadata.Id
        {
            get { return "201802071704470_Add other entities and configurations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
